### ISSUE TITLE
"unrecognised content at end of stream" for Mac/Windows team

### ISSUE THREAD

**Issue by varya** [wKich/creevey#151]
The screenshots made under Unix (Mac) don't work on Windows. Every single story gave this error

```
[START:chrome.desktop:4468] Utilities/Typography/Link
[FAIL:chrome.desktop:4468] Utilities/Typography/Link
   Error: unrecognised content at end of stream
    at module.exports.SyncReader.process (node_modules\pngjs\lib\sync-reader.js:43:11)
    at module.exports (node_modules\pngjs\lib\parser-sync.js:68:10)
    at Object.exports.read (node_modules\pngjs\lib\png-sync.js:7:10)
    at compareImages (node_modules\creevey\lib\server\worker\chai-image.js:48:39)
    at assertImage (node_modules\creevey\lib\server\worker\chai-image.js:99:11)
    at Proxy.matchImage (node_modules\creevey\lib\server\worker\chai-image.js:107:28)
    at Context.storyTest (node_modules\creevey\lib\server\stories.js:43:5)
```

![Screenshot_2021-05-24 Creevey](https://user-images.githubusercontent.com/27215/119344083-e4d63e80-bc9f-11eb-90a5-09e63014e7c0.png)

Perhaps it is related to https://github.com/lukeapage/pngjs/issues/235 ?

We use

node v14.15.4
npm 6.14.4
creevey 0.7.28

**Comment by hamitzor** [comment]
Having the same problem.

**Comment by hamitzor** [comment]
I strongly believe Git LFS has something to do with this, as @varya pointed out, because when I have PNGs that have not been interacted with Git LFS the error disappears.

**Comment by mwiemer-microsoft** [comment]
Yes, I got the same with an Azure Pipelines build when we used Git LFS in our repo. Removing Git LFS resolved the problem.

**Comment by blingerson** [comment]
I have this issue without git LFS being installed on our repo. Anyone have a workaround?

**Comment by srpalwaidynamite** [comment]
I have this issue without git LFS being installed on our repo.
