### ISSUE TITLE
DevToolsActivePort file doesn't exist - Mac OS

### ISSUE THREAD

**Issue by cassiourugit** [wKich/creevey#160]
Hi, i have a storybook project, installed creevey
started storybook
and, when I run creevey, (yarn creevey --ui)

It shows this:
[CreeveyMaster]: Pull docker images
✔ aerokube/selenoid:latest-release: Pull complete
[CreeveyMaster]: Pull docker images
✔ selenoid/chrome:latest: Pull complete
[CreeveyMaster]: Starting with pid 1029
[CreeveyWorker]: Starting chrome:1030
[FAIL:1030] WebDriverError: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)

Anyone knows how to solve this? I've looked all over the place, but found no working answer.

I'm running this over a Mac mini with Big Sur 11.4 and M1 Chip

**Comment by wKich** [comment]
Hi, thank you for the report. It seems you faced this issue https://github.com/aerokube/selenoid/issues/1109. Creevey uses selenoid under the hood.

You can try to install Rosetta with `softwareupdate --install-rosetta` and then set the environment variable before starting Creevey `export DOCKER_DEFAULT_PLATFORM=linux/amd64`. It should enable x86 emulation in docker.

Unfortunately, I don't have M1 Mac to reproduce or make sure if it works.

**Comment by cassiourugit** [comment]
Hi, thanks for the quick reply!

I did those steps, but still facing the issue.

I found this 3 options inside creevey

 1- 
`useDocker: boolean;`

2- 
`Custom selenoid docker image -- @default 'aerokube/selenoid:latest-release' -- dockerImage: string;`

3- 
`Should Creevey pull docker images or use local ones -- @default true -- pullImages: boolean;`

Is it possible to use any of those options so that I can use containers that I have already installed instead of the default ones? 
Or maybe don't use docker at all, using a local cromedriver?

Ps, sorry about my English, is not my native language.

**Comment by wKich** [comment]
1. It could be used as a solution, to run selenoid without docker or without selenoid at all, directly use chromedriver. But screenshots will be dependent on your system, so if tests are run on CI or by someone else, they will fail.
2. Yep, you can try using custom selenoid images, as described in selenoid issue. But I think the issue is in a browser image, so you might want to define your custom browser image, like this.
```js
// creevey.config.js
module.exports = {
  browsers: {
    chrome: {
      dockerImage: 'name-of-your-chromedriver-image'
    }
  }
}
```
Or it could be another way. Instead of using selenoid docker image, use chromedriver image directly. But I haven't thought about this way before, so you can't have more than one parallel session. I recommend it as a fallback if defining a custom browser image wouldn't help.

3. It's used to skip pulling images from docker registry every time. It helps if you want to use images aren't exist in registry.

PS. Don't worry. I'm not a native speaker too :)

**Comment by yozi-developer** [comment]
According to the issue, it does not work yet
https://github.com/SeleniumHQ/selenium/issues/9733

**Comment by daks01** [comment]
I reproduced a similar error on gitlab ci + docker + selenoid

```
[Creevey:119] ERROR => WebDriverError: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/builds/websites/site-shot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/builds/websites/site-shot/node_modules/selenium-webdriver/lib/http.js:642:13)
    at Executor.execute (/builds/websites/site-shot/node_modules/selenium-webdriver/lib/http.js:568:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I will write more details later

**Comment by fifle** [comment]
Hey everyone! Are there any update on those issues? 
The problem still persists in combination of Macbook on M1 chip + Docker + Selenium under Codeception.

**Comment by TheMontanyes** [comment]
@wKich, Hello!
The problem is still relevant, is there any news on the solution?
I tried all the options, also emulated via arch x64

**Comment by okletzmayr** [comment]
Looks like ARM images for selenium have been released ~1 month ago:
https://github.com/SeleniumHQ/docker-selenium/issues/1076#issuecomment-1053189663

I managed to get to the Screenshot stage on `0.8.0-beta.0` M1 with this `.creevey/config.js`:
```js
module.exports = {
  browsers: {
    chrome: {
      browserName: 'chrome',
      dockerImage: 'seleniarm/standalone-chromium:4.1.3-20220331'
    }
  }
}
```
The workers look like they work if they can screenshot stuff, but I *think* `aerokube/selenoid` is causing problems since this image is still `amd64`. I haven't looked too deeply into this, but wanted to share anyways.
