### ISSUE TITLE
[Creevey:21879] ERROR => TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by xArt2150** [wKich/creevey#192]
Hi

Tried to run Creevey (on Linux) and have an exception described in the title.

I follow the instruction from the readme:
1. add the creevey
2. add it to the storybook config
3. run the storybook
4. and then run the creevey

Stack:

`
yarn creevey --ui

[Creevey:21879] INFO => Pull docker images
✔ aerokube/selenoid:latest-release: Pull complete
[Creevey:21879] INFO => Pull docker images
✔ selenoid/chrome:latest: Pull complete
[Creevey:21879] ERROR => TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at createSelenoidConfig (/home/art/projects/helios/orbit-components/.yarn/cache/creevey-npm-0.7.39-fe9bc3e472-71ab9c68a4.zip/node_modules/creevey/lib/cjs/server/selenium/selenoid.js:38:43)
    at Object.startSelenoidContainer (/home/art/projects/helios/orbit-components/.yarn/cache/creevey-npm-0.7.39-fe9bc3e472-71ab9c68a4.zip/node_modules/creevey/lib/cjs/server/selenium/selenoid.js:168:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object._default [as default] (/home/art/projects/helios/orbit-components/.yarn/cache/creevey-npm-0.7.39-fe9bc3e472-71ab9c68a4.zip/node_modules/creevey/lib/cjs/server/docker.js:121:18)
    at async _default (/home/art/projects/helios/orbit-components/.yarn/cache/creevey-npm-0.7.39-fe9bc3e472-71ab9c68a4.zip/node_modules/creevey/lib/cjs/server/index.js:48:5)
`

Looks like something wrong [here](https://github.com/wKich/creevey/blob/748d8968c645ee684cec5dcd899d2de749d5e2c6/src/server/selenium/selenoid.ts#L23) with `getCreeveyCache`, or maybe anywhere else?

**Comment by wKich** [comment]
Hi. I'm sorry for the late response. That is strange because I use the same packages https://www.npmjs.com/package/find-cache-dir that is used in Storybook to resolve `.cache` directory inside `node_modules`. Oh, I see, the modules paths look like you use yarn@2 or yarn@3 and I never tested creevey with them

**Comment by xArt2150** [comment]
@wKich yeah, we are using yarn 3.1.1

**Comment by d-woegerbauer** [comment]
Hi, is there any update to this issue yet, because I am also experiencing this issue with creevey?
![image](https://user-images.githubusercontent.com/56993269/148638510-aa1049af-3f3b-4428-9bad-a0281a7526c1.png)
